discord_channel_name_to_id = {
    "bot_home": 1234981709473255555,
    "devs": 1052682106351919127,
    "murlock": 1052682106351919126,
    "sportivii": 1229309812077101079,
}

strava_activity_to_emoji = {
    'AlpineSki': '⛷️',
    'BackcountrySki': '⛷️',
    'Canoeing': '🛶',
    'Crossfit': '🏋️',
    'EBikeRide': '⚡️',
    'Elliptical': '🚴',
    'Golf': '⛳',
    'Handcycle': '🚴',
    'Hike': '🥾',
    'IceSkate': '⛸️',
    'InlineSkate': '🛼',
    'Kayaking': '🛶',
    'Kitesurf': '🪁',
    'NordicSki': '🎿',
    'Ride': '🚴',
    'RockClimbing': '🧗',
    'RollerSki': '🎿',
    'Rowing': '🚣',
    'Run': '🏃',
    'Sail': '⛵',
    'Skateboard': '🛹',
    'Snowboard': '🏂',
    'Snowshoe': '🏂',
    'Soccer': '⚽',
    'StairStepper': '🏃',
    'StandUpPaddling': '🏄',
    'Surfing': '🏄',
    'Swim': '🏊',
    'Velomobile': '🚴',
    'VirtualRide': '🚴',
    'VirtualRun': '🏃',
    'Walk': '🚶',
    'WeightTraining': '🏋️',
    'Wheelchair': '♿',
    'Windsurf': '🏄',
    'Workout': '🏋️',
    'Yoga': '🧘',
}
